[package]
name = "hayro-syntax"
version = "0.4.0"
description = "A low-level crate for reading PDF files."
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
log = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
hayro-common = { workspace = true }
zune-jpeg = { workspace = true }
flate2 = { workspace = true }
hayro-jpeg2000 = { workspace = true, features = ["simd"] }

[lints]
workspace = true

[dev-dependencies]
sha2 = "0.10"
md5 = "0.8"
aes = "0.8.4"
cbc = "0.1.2"
