[package]
name = "hayro-ccitt"
version = "0.2.0"
description = "A decoder for group 3 and group 4 CCITT images."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "README.md"

[lints]
workspace = true
