name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  checks:
    name: Check clippy, formatting, and documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.92.0
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - run: RUSTFLAGS="-D warnings" cargo clippy --workspace --exclude hayro-demo --tests --examples
      - run: cargo fmt --check --all
      - run: RUSTFLAGS="-D warnings" cargo doc --workspace --exclude hayro-demo --no-deps
      - run: RUSTFLAGS="-D warnings" cargo hack check --each-feature --workspace --exclude hayro-demo
        
  no_std:
    name: Check no_std compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.92.0
        with:
          targets: x86_64-unknown-none
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -p hayro-ccitt --target x86_64-unknown-none
      - run: cargo check -p hayro-jbig2 --no-default-features --target x86_64-unknown-none
      - run: cargo check -p hayro-jpeg2000 --no-default-features --target x86_64-unknown-none

  load_tests:
    name: Run CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.92.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo test -p hayro-tests -- "load::"
